name: Build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      run: pip install tox

    - name: Run tox on 3.11
      if: ${{ matrix.python-version == '3.11' }}
      run: tox -e py-{jax3,jax4}

    - name: Run tox on 3.10
      if: ${{ matrix.python-version == '3.10' }}
      run: tox -e py-{tf29,tf211}

    - name: Run tox on 3.9
      if: ${{ matrix.python-version == '3.9' }}
      run: tox -e py-{tf26}

    - name: Run tox on 3.8
      if: ${{ matrix.python-version == '3.8' }}
      run: tox -e py-{jax3,jax4,tf26,tf211}
