name: Tox test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.12']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install rye
      uses: eifinger/setup-rye@v3

    - name: Run tox
      run: |
        rye install tox-gh-actions --include-dep tox
        tox -- -x -m vec
